jobs:
  - name: script-1
    type: runSh
    allowPublicAccess: true
    steps:
      - IN: trigger-1
      - IN: myParams
      - IN: dv-image
      - IN: sample-script-3
#      - IN: testprivate_gitRepo
#      - IN: sampleJav_gitRepo
#      - OUT: sampleJav_ciRepo
#      - OUT: testprivate_ciRepo
      - TASK:
        - script: printenv
        - script: echo "ran ls 1234"
        - script: echo "lololo"
        - script: for i in {1..10}; do echo "$i"; done
        - script: echo "versionName=$BUILD_NUMBER" > /build/state/script-1.env
        - script: echo "versionName $BUILD_NUMBER"
    on_success:
      - script: echo "on_success"
      - scirpt: echo $DVIMAGE_INTEGRATION_USERNAME
    always:
      - script: echo "always"
      - script: echo "lol"
      - NOTIFY: notification-slack
  - name: dv-man-versionName
    type: manifest
    steps:
      - IN: script-1
      - IN: dv-image
        pull: false
        versionName: latest
    on_success:
      - script: echo "on_success_man"
  - name: split-branch-hippo-cms-runSh
    type: runSh
    allowPublicAccess: true
    steps:
      - IN: dv-man-versionName
      - IN: trigger-1
      - IN: dv-image
      - IN: sample-script-3
      - IN: rc_api_params
      - TASK:
        - script: ./IN/sample-script-3/gitRepo/check_queue.sh rc
        - script: ./IN/sample-script-3/gitRepo/echo.sh
    on_success:
      - script: echo "success"
    on_failure:
      - script: echo "on_failure"
 # - name: testprivate_runCI
 #   type: runCI
 #   steps:
 #     - IN: script-1
 #     - IN: testprivate_ciRepo
 # - name: sampleJav_runCI
 #   type: runCI
 #   steps:
 #     - IN: script-1
 #     - IN: sampleJav_ciRepo
