jobs:
  - name: script-1
    type: runSh
    steps:
      - IN: sample-script-3
      - IN: trigger-1
      - TASK:
        - script: ls
        - script: echo "ran ls 1234"
    on_success:
      - NOTIFY: notification-slack
    always:
      - script: echo "always"
      - NOTIFY: notification-slack
      - script: echo "lol"
      - NOTIFY: email
  - name: dv-man-versionName
    type: manifest
    steps:
      - IN: dv-image
        pull: false
        versionName: latest
    always:
      - NOTIFY: notification-slack
  - name: script-2
    type: runSh
    steps:
      - IN: sample-script-3
      - IN: trigger-1
      - IN: dv-image
      - TASK:
        - script: pwd
        - script: echo "ran ls 1234"
    always:
      - NOTIFY: email
