jobs:
  - name: script-1
    type: runSh
    steps:
      - IN: trigger-1
      - TASK:
        - script: ls
        - script: echo "ran ls 12345"
        - script: docker ps -a
        - script: echo "lololo"
    on_success:
      - script: echo "on_success"
    always:
      - script: echo "always"
      - script: echo "lol"
      - NOTIFY: notification-slack
  - name: dv-man-versionName
    type: manifest
    steps:
      - IN: script-1
      - IN: dv-image
        pull: false
        versionName: latest
    on_success:
      - script: echo "on_success_man"
  - name: script-2
    type: runSh
    steps:
      - IN: dv-man-versionName
      - IN: trigger-1
      - IN: dv-image
      - IN: sample-script-3
      - TASK:
        - script: pwd
        - scirpt: ./IN/sample-script-3/gitRepo/echo.sh
        - script: echo "ran ls 1234"
        - script: docker ps -a
        - script: exit 1
    on_failure:
      - script: echo "on_failure"
       
