jobs:
  - name: script-1
    type: runSh
    steps:
      - IN: sample-script-3
      - IN: trigger-1
      - TASK:
        - script: ls
        - script: echo "ran ls 123"
        - script: pwd
        - script: ./IN/sample-script-3/gitRepo/echo.sh
    on_success:
      - ohce
  
  - name: dv-man-versionName
    type: manifest
    steps:
      - IN: dv-image
        pull: false
        versionName: latest
      - TASK: managed
      - IN: trigger-1
      
  - name: dv-test
    type: deploy
    steps:
      - IN: dv-man-versionName
      - IN: env-test
      - TASK: managed

  - name: release-1
    type: release
    steps:
      - IN: version-resource
      - IN: dv-test
      - TASK: managed
        bump: minor
        
  - name: deploy-2
    type: deploy
    steps:
      - IN: release-1
      - IN: env-test
      - TASK: managed
      
  - name: release-2
    type: release
    steps:
      - IN: version-resource
      - IN: deploy-2
      - TASK: managed
        bump: minor
