jobs:
  - name: script-1
    type: runSh
    steps:
      - IN: trigger-1
      - TASK:
        - script: ls
        - script: echo "ran ls 1234"
        - script: docker ps
    always:
      - script: echo "always"
      - script: echo "lol"
  - name: dv-man-versionName
    type: manifest
    steps:
      - IN: script-1
      - IN: dv-image
        pull: false
        versionName: latest
    always:
      - NOTIFY: email
  - name: script-2
    type: runSh
    steps:
      - IN: dv-man-versionName
      - IN: trigger-1
      - IN: dv-image
      - TASK:
        - script: pwd
        - script: echo "ran ls 1234"
