jobs:
  - name: script-1
    type: runSh
    steps:
      - IN: trigger-1
      - IN: myParams
      - IN: dv-image
      - IN: sample-script-3
      - TASK:
        - script: printenv
        - script: sleep 180
        - script: echo "ran ls 12345"
        - script: echo "lololo"
        - script: for i in {1..500}; do echo "$i"; done
    on_success:
      - script: echo "on_success"
      - scirpt: echo $DVIMAGE_INTEGRATION_USERNAME
    always:
      - script: echo "always"
      - script: echo "lol"
      - NOTIFY: notification-slack
  - name: dv-man-versionName
    type: manifest
    steps:
      - IN: script-1
      - IN: dv-image
        pull: false
        versionName: latest
    on_success:
      - script: echo "on_success_man"
  - name: split-branch-hippo-cms-runSh
    type: runSh
    steps:
      - IN: dv-man-versionName
      - IN: trigger-1
      - IN: dv-image
      - IN: sample-script-3
      - IN: rc_api_params
      - TASK:
        - script: ./IN/sample-script-3/gitRepo/check_queue.sh rc
        - script: ./IN/sample-script-3/gitRepo/echo.sh
    on_success:
      - script: echo "success"
    on_failure:
      - script: echo "on_failure"
  #- name: testprivate_runCI
  #  type: runCI
  #  steps:
  #    - IN: split-branch-hippo-cms-runSh
       
