jobs:
  - name: script-1
    type: runSh
    steps:
      - IN: trigger-1
      - IN: myParams
      - IN: dv-image
      - TASK:
        - script: printenv
        - script: echo "ran ls 12345"
        - script: echo "lololo"
    on_success:
      - script: echo "on_success"
      - scirpt: echo $DVIMAGE_INTEGRATION_USERNAME
    always:
      - script: echo "always"
      - script: echo "lol"
      - NOTIFY: notification-slack
  - name: dv-man-versionName
    type: manifest
    steps:
      - IN: script-1
      - IN: dv-image
        pull: false
        versionName: latest
    on_success:
      - script: echo "on_success_man"
  - name: split-branch-hippo-cms-runSh
    type: runSh
    steps:
      - IN: dv-man-versionName
      - IN: trigger-1
      - IN: dv-image
      - IN: sample-script-3
      - IN: rcParams
      - TASK:
        - script: pwd
        - script: echo $RCPARAMS_PARAMS_APIURL
        - scirpt: ./IN/sample-script-3/gitRepo/check_queue.sh
        - script: cd /IN/sample-script-3/gitRepo && ls
        - scirpt: ./IN/sample-script-3/gitRepo/echo.sh
        - script: echo "ran ls 1234"
        - script: docker ps -a
    on_success:
      - NOTIFY: notification-slack
    on_failure:
      - NOTIFY: notification-slack
      - script: echo "on_failure"
  #- name: testprivate_runCI
  #  type: runCI
  #  steps:
  #    - IN: split-branch-hippo-cms-runSh
       
